# Site settings
title: Loni
SEOTitle: 山顶洞洞主 | Loni
header-img: img/home-bg2.jpg
email: niwota568@163.com
description: "这应该是自我介绍的地方"
keyword: "Loni, Loni Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
url: "http://www.loni.club"              # your host, for absolute URL
baseurl: "/"                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username:     huxpro
zhihu_username:     buduvip
github_username:    Loni0527
#twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown 设置
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: redcarpet
redcarpet:
    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
# kramdown:
#   input: GFM                            # use Github Flavored Markdown !important



# Disqus 设置
disqus_username: loni

# 网易设置
netease_comment: false



# 分析设置
# 百度分析 
# ba_track_id: [your track id]

# 谷歌分析
ga_track_id: 'UA-49627206-1'            # 格式: UA-xxxxxx-xx
ga_domain: huangxuan.me



# 边栏设置
sidebar: true                           # 是否使用边栏.
sidebar-about-description: "断剑重铸之日，骑士归来之时"
sidebar-avatar: /img/avatar-hux-dog.jpg      # 使用绝对 URL, 如 '/' 或 '/about/'



# 特色标签
featured-tags: true                     # 是否使用功能标记
featured-condition-size: 1              # 如果标记的大小大于此条件值, 则将对其进行特征码



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
    #     title: "乱序",
    #     href: "http://mida.re/"
    # },{
    #     title: "前端外刊评论",
    #     href: "http://qianduan.guru/"
    # },{
    #     title: "天镶的博客",
    #     href: "http://lingyu.wang/"
    # },{
    #     title: "Luke 的自留地",
    #     href: "http://hmqk1995.github.io"
    # },{
    #     title: "Ebn's Blog",
    #     href: "http://ebnbin.com/"
    # },{
    #     title: "SmdCn's Blog",
    #     href: "http://blog.smdcn.net"
    # },{
    #     title: "David's Game",
    #     href: "https://www.ruoyaowu.com/"
    # },{
    #     title: "DHong Say",
    #     href: "http://dhong.co"
    # },{
    #     title: "尹峰以为",
    #     href: "http://ingf.github.io/"
    # },{
    #     title: "解旻的博客",
    #     href: "http://xieminis.me/"
    }
]
